# Generated by Django 5.2.5 on 2025-09-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_subtask_time_estimate_subtasktimeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='time_estimate',
        ),
        migrations.DeleteModel(
            name='SubTaskTimeEntry',
        ),
    ]
