# Generated by Django 5.2.5 on 2025-09-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_subtask_deadline_subtask_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='time_estimate',
            field=models.PositiveIntegerField(default=0, help_text='Estimated time in hours'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='time_tracked',
            field=models.PositiveIntegerField(default=0, help_text='Actual tracked time in hours'),
        ),
    ]
