# Generated by Django 5.2.5 on 2025-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_subtask_time_estimate_subtask_time_tracked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='time_estimate',
        ),
        migrations.AddField(
            model_name='subtask',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='time_tracked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
