# Generated by Django 5.2.5 on 2025-10-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_subtask_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='from_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='to_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='time_tracked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
