# Generated by Django 5.2.5 on 2025-10-13 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_subtask_from_datetime_subtask_to_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='to_datetime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='from_datetime',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='time_tracked',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
    ]
