# Generated by Django 5.2.5 on 2025-10-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_to_datetime_subtask_end_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.FloatField(default=0.0, help_text='Estimated time in hours'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_tracked',
            field=models.FloatField(default=0.0, help_text='Total tracked time from subtasks in hours'),
        ),
    ]
