# Generated by Django 5.2.5 on 2025-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_task_estimated_time_remove_task_time_tracked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='tracked_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
