# Generated by Django 5.2.5 on 2025-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_task_end_date_task_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='tracked_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
